# Generated by Django 3.0.5 on 2020-05-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='diff_level',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
